AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'lib/tasks/**/*'
    - 'test/**/*'
    - 'spec/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
