sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
env:
  # - DB=sqlite
  # - DB=mysql
  - RSPEC_VERSION=3.0
  - RSPEC_VERSION=3.7
  - RSPEC_VERSION=master
cache: bundler
before_install:
  - gem update --system # https://github.com/sickill/rainbow/issues/49
  - gem install bundler
before_script:
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate
script:
  - RAILS_ENV=test bundle exec rspec
notifications:
  email: false
